### ISSUE TITLE
Filters to have AND logic rather than OR

### ISSUE THREAD

**Issue by apricot13** [wearefuturegov/Outpost-Platform#19]
# Description of ~~request or~~ change

Currently in Scout the filters work on `or` logic, this issue describes a request to add in `AND` logic support as well.

**Original request:**

> For example currently, [when someone selects autism and deafness](https://directory.familyinfo.buckinghamshire.gov.uk/), the results shown have both listed and not those that are only both.

# Scope

This issue only covers filters, it does not cover taxonomies, see [Caveats](#Caveats)

# User Story

**As a user**, **I want to** be able to request a list of services that have specific filters assigned to them. Specifically, **I want to** be able to filter services by the suitability tag, **so that** I can find services that are appropriate for my needs. Additionally, **I want to** be able to filter services by taxonomy tags, so that I can find services that are relevant to my interests.

# Definition of Done

* Implement API calls that allow users to filter services by AND, OR methods.
* Ensure that the API calls return the expected results based on the filter parameters.
* Add documentation for these filter parameters to the Outpost API documentation.

# Acceptance Criteria

Using this data:

```json
[
  {
    "name": "Service A",
    "suitabilities": [
      {
        "name": "Suitability 1"
      },
      {
        "name": "Suitability 2"
      }
    ]
  },
  {
    "name": "Service B",
    "suitabilities": [
      {
        "name": "Suitability 1"
      }
    ]
  },
  {
    "name": "Service C",
    "suitabilities": [
      {
        "name": "Suitability 2"
      }
    ]
  }
]

```

## Scenario 1: Requesting a list of services with `suitability_1` AND `suitability_2` assigned to them

* Given that I am a user of the Outpost API
* When I make a GET request to the "/services" endpoint with the following parameters:

```sh
 suitabilities=suitability_1,suitability_2
```
* Then the API should return a list of services that have both `suitability_1` AND `suitability_2` assigned to them.

```json
[
  {
    "name": "Service A",
    "suitabilities": [
      {
        "name": "Suitability 1"
      },
      {
        "name": "Suitability 2"
      }
    ]
  }
]
```

## Scenario 2: Requesting a list of services with `suitability_1` OR `suitability_2` assigned to them

* Given that I am a user of the OutpostAPI
* When I make a GET request to the "/services" endpoint with the following parameters:
```
?suitabilities=suitability_1&suitabilities=suitability_2
```
or
```
?suitabilities=suitability_1|suitability_2
```
Then the API should return a list of services that have either `suitability_1` OR `suitability_2` assigned to them.

Note: In all of the above scenarios, the API should return only the services that match the specified filter parameters. Any services that do not match the filters should be excluded from the results.

```json
[
  {
    "name": "Service A",
    "suitabilities": [
      {
        "name": "Suitability 1"
      },
      {
        "name": "Suitability 2"
      }
    ]
  },
  {
    "name": "Service B",
    "suitabilities": [
      {
        "name": "Suitability 1"
      }
    ]
  },
  {
    "name": "Service C",
    "suitabilities": [
      {
        "name": "Suitability 2"
      }
    ]
  }
]

```

# Notes

## [Looking into how ORUK uses taxonomies](https://developers.openreferraluk.org/UseOfTaxonomies/)

It doesn't specify whether or not to default to 'AND' and 'OR' but it does seem to imply AND/OR, which is what Outpost currently supports.

[Examples given](https://developers.openreferraluk.org/UseOfTaxonomies/#querying-apis-by-taxonomy-terms) here are:

```
/services/?service_types=esdServiceType:298service_types=esdServiceType:1755 
```

finds services of types: [298 - Carers support groups](http://id.esd.org.uk/service/298)  **and/or**  [1755 - Carers assessment](http://id.esd.org.uk/service/1755).

```
/services/?circumstance=esdCircumstance:Gender_Female&circumstance=esdCircumstance:AddictSubstanceAbuser_Smoking 
```

finds services of types associated with circumstance [Gender_Female - Female](http://id.esd.org.uk/circumstance/Gender_Female) **and/or** [AddictSubstanceAbuser_Smoking - Smoker](http://id.esd.org.uk/circumstance/AddictSubstanceAbuser_Smoking).

```
/services/?need=esdNeed:69&esdNeeds=need:71 
```

finds services of types associated with needs [69 - Social inclusion](http://id.esd.org.uk/need/69) **and/or** [71 - Community facilities](http://id.esd.org.uk/need/71)

## Caveats

Outpost doesn't currently support vocabularies but will do in the future so any solution should bear this in mind

> Hence this call is used to find all services of service type 298 in the LGA Service Type list:
> 
> `services/?taxonomy_id=esdServiceType:242&taxonomy_type=service&vocabulary=esdServiceTypes`
> 
> Note that all the above filter parameters are applied with a Boolean AND operator. Hence the above syntax cannot be used to find services with one of a number of given service types via a single API call.

In the ORUK standard when you request a list of services by taxonomy you must include three pieces of data (the taxonomy ID, the taxonomy type, and the vocabulary) in order to return a result

```json
{
  "taxonomy_id": "esdServiceType:242",
  "taxonomy_type": "service",
  "vocabulary": "esdServiceTypes"
}
```

# Tasks

- [ ] Clarify ORUK and/or on filters (and taxonomies for future reference)
- [ ] Apply change to Suitabilities
- [ ] Apply change to Send needs
- [ ] Apply change to Accessibilities
- [ ] Apply change to Days
- [ ] Update targetDirectories field to match this logic
- [ ] For Scout we will set a flag like `filterCondition: and|or` on each filter box, and possibly a global option as well

# Future work

- UX and Research work to be done around how to best present this information to the user on the frontend

**Comment by apricot13** [comment]
> My understanding is that query parameters should be combined with a Boolean AND - so all filter conditions should be valid for all results.
> 
> So if you want to do an OR, you need to do two (or more) queries and combine the responses.


> it is boolean AND.
> 
> /services?taxonomy_id=XXX&organization_id=YYY
> 
> So this is searching for taxonomy_id XXX AND organization_id YYY
